// Source https://bulbapedia.bulbagarden.net/wiki/List_of_locations_by_index_number_(Generation_I)

export const Locations: { [key: number]: string } = {
  0x00: 'Pallet Town',
  0x01: 'Viridian City',
  0x02: 'Pewter City',
  0x03: 'Cerulean City',
  0x04: 'Lavender Town',
  0x05: 'Vermilion City',
  0x06: 'Celadon City',
  0x07: 'Fuchsia City',
  0x08: 'Cinnabar Island',
  0x09: 'Pokémon League',
  0x0a: 'Saffron City',
  0x0b: 'Unused Fly location',
  0x0c: 'Route 1',
  0x0d: 'Route 2',
  0x0e: 'Route 3',
  0x0f: 'Route 4',
  0x10: 'Route 5',
  0x11: 'Route 6',
  0x12: 'Route 7',
  0x13: 'Route 8',
  0x14: 'Route 9',
  0x15: 'Route 10',
  0x16: 'Route 11',
  0x17: 'Route 12',
  0x18: 'Route 13',
  0x19: 'Route 14',
  0x1a: 'Route 15',
  0x1b: 'Route 16',
  0x1c: 'Route 17',
  0x1d: 'Route 18',
  0x1e: 'Sea Route 19',
  0x1f: 'Sea Route 20',
  0x20: 'Sea Route 21',
  0x21: 'Route 22',
  0x22: 'Route 23',
  0x23: 'Route 24',
  0x24: 'Route 25',
  0x25: "Red's house (first floor)",
  0x26: "Red's house (second floor)",
  0x27: "Blue's house",
  0x28: "Professor Oak's Lab",
  0x29: 'Pokémon Center (Viridian City)',
  0x2a: 'Poké Mart (Viridian City)',
  0x2b: 'School (Viridian City)',
  0x2c: 'House 1 (Viridian City)',
  0x2d: 'Pokémon Gym (Viridian City)',
  0x2e: "Diglett's Cave (Route 2 entrance)",
  0x2f: 'Gate (Viridian City/Pewter City) (Route 2)',
  0x30: "Oak's Aide House 1 (Route 2)",
  0x31: 'Gate (Route 2)',
  0x32: 'Gate (Route 2/Viridian Forest) (Route 2)',
  0x33: 'Viridian Forest',
  0x34: 'Pewter Museum (floor 1)',
  0x35: 'Pewter Museum (floor 2)',
  0x36: 'Pokémon Gym (Pewter City)',
  0x37: 'House with disobedient Nidoran♂ (Pewter City)',
  0x38: 'Poké Mart (Pewter City)',
  0x39: 'House with two Trainers (Pewter City)',
  0x3a: 'Pokémon Center (Pewter City)',
  0x3b: 'Mt. Moon (Route 3 entrance)',
  0x3c: 'Mt. Moon',
  0x3d: 'Mt. Moon',
  0x3e: 'Invaded house (Cerulean City)',
  0x3f: 'Polihirl for Jynx trade house (Red/Blue)\nBulbasaur adoption house (Pokémon Yellow)',
  0x40: 'Pokémon Center (Cerulean City)',
  0x41: 'Pokémon Gym (Cerulean City)',
  0x42: 'Bike Shop (Cerulean City)',
  0x43: 'Poké Mart (Cerulean City)',
  0x44: 'Pokémon Center (Route 4)',
  0x45: 'Invaded house - alternative music (Cerulean City)',
  0x46: 'Saffron City Gate (Route 5)',
  0x47: 'Entrance to Underground Path (Kanto Routes 5-6) (Route 5)',
  0x48: 'Daycare Center (Route 5)',
  0x49: 'Saffron City Gate (Route 6)',
  0x4a: 'Entrance to Underground Path (Route 6)',
  0x4b: 'Entrance to Underground Path 2 (Route 6)',
  0x4c: 'Saffron City Gate (Route 7)',
  0x4d: 'Entrance to Underground Path (Route 7)',
  0x4e: 'Entrance to Underground Path 2 (Route 7)',
  0x4f: 'Saffron City Gate (Route 8)',
  0x50: 'Entrance to Underground Path (Route 8)',
  0x51: 'Pokémon Center (Rock Tunnel)',
  0x52: 'Rock Tunnel',
  0x53: 'Power Plant',
  0x54: 'Gate 1F (Route 11-Route 12)',
  0x55: "Diglett's Cave (Vermilion City entrance)",
  0x56: 'Gate 2F (Route 11-Route 12)',
  0x57: 'Gate (Route 12-Route 13)',
  0x58: 'Sea Cottage',
  0x59: 'Pokémon Center (Vermilion City)',
  0x5a: 'Pokémon Fan Club (Vermilion City)',
  0x5b: 'Poké Mart (Vermilion City)',
  0x5c: 'Pokémon Gym (Vermilion City)',
  0x5d: 'House with Pidgey (Vermilion City)',
  0x5e: 'Vermilion Harbor (Vermilion City)',
  0x5f: 'S.S. Anne 1F',
  0x60: 'S.S. Anne 2F',
  0x61: 'S.S. Anne 3F',
  0x62: 'S.S. Anne B1F',
  0x63: 'S.S. Anne (Deck)',
  0x64: 'S.S. Anne (Kitchen)',
  0x65: "S.S. Anne (Captain's room)",
  0x66: "S.S. Anne 1F (Gentleman's room)",
  0x67: "S.S. Anne 2F (Gentleman's room)",
  0x68: "S.S. Anne B1F (Sailor/Fisherman's room)",
  0x69: 'Unused (Victory Road)',
  0x6a: 'Unused (Victory Road)',
  0x6b: 'Unused (Victory Road)',
  0x6c: 'Victory Road (Route 23 entrance)',
  0x6d: 'Unused (Pokémon League)',
  0x6e: 'Unused (Pokémon League)',
  0x6f: 'Unused (Pokémon League)',
  0x70: 'Unused (Pokémon League)',
  0x71: "Lance's Elite Four room",
  0x72: 'Unused (Pokémon League)',
  0x73: 'Unused (Pokémon League)',
  0x74: 'Unused (Pokémon League)',
  0x75: 'Unused (Pokémon League)',
  0x76: 'Hall of Fame',
  0x77: 'Underground Path (Route 5-Route 6)',
  0x78: "Blue's room",
  0x79: 'Underground Path (Route 7-Route 8)',
  0x7a: 'Celadon Department Store 1F',
  0x7b: 'Celadon Department Store 2F',
  0x7c: 'Celadon Department Store 3F',
  0x7d: 'Celadon Department Store 4F',
  0x7e: 'Celadon Department Store Rooftop Square',
  0x7f: 'Celadon Department Store Lift',
  0x80: 'Celadon Mansion 1F',
  0x81: 'Celadon Mansion 2F',
  0x82: 'Celadon Mansion 3F',
  0x83: 'Celadon Mansion 4F',
  0x84: 'Celadon Mansion 4F (Eevee building)',
  0x85: 'Pokémon Center (Celadon City)',
  0x86: 'Pokémon Gym (Celadon City)',
  0x87: 'Rocket Game Corner (Celadon City)',
  0x88: 'Celadon Department Store 5F',
  0x89: 'Prize corner (Celadon City)',
  0x8a: 'Restaurant (Celadon City)',
  0x8b: 'House with Team Rocket members (Celadon City)',
  0x8c: 'Hotel (Celadon City)',
  0x8d: 'Pokémon Center (Lavender Town)',
  0x8e: 'Pokémon Tower F1',
  0x8f: 'Pokémon Tower F2',
  0x90: 'Pokémon Tower F3',
  0x91: 'Pokémon Tower F4',
  0x92: 'Pokémon Tower F5',
  0x93: 'Pokémon Tower F6',
  0x94: 'Pokémon Tower F7',
  0x95: "Mr. Fuji's house (Lavender Town)",
  0x96: 'Poké Mart (Lavender Town)',
  0x97: "House with NPC discussing Cubone's mother",
  0x98: 'Poké Mart (Fuchsia City)',
  0x99: 'House with NPCs discussing Bill (Fuchsia City)',
  0x9a: 'Pokémon Center (Fuchsia City)',
  0x9b: "Warden's house (Fuchsia City)",
  0x9c: 'Safari Zone gate (Fuchsia City)',
  0x9d: 'Pokémon Gym (Fuchsia City)',
  0x9e: 'House with NPCs discussing Baoba (Fuchsia City)',
  0x9f: 'Seafoam Islands',
  0xa0: 'Seafoam Islands',
  0xa1: 'Seafoam Islands',
  0xa2: 'Seafoam Islands',
  0xa3: 'Vermilion City Fishing Brother',
  0xa4: 'Fuchsia City Fishing Brother',
  0xa5: 'Pokémon Mansion (1F)',
  0xa6: 'Pokémon Gym (Cinnabar Island)',
  0xa7: 'Pokémon Lab (Cinnabar Island)',
  0xa8: 'Pokémon Lab - Trade room (Cinnabar Island)',
  0xa9: 'Pokémon Lab - Room with scientists (Cinnabar Island)',
  0xaa: 'Pokémon Lab - Fossil resurrection room (Cinnabar Island)',
  0xab: 'Pokémon Center (Cinnabar Island)',
  0xac: 'Poké Mart (Cinnabar Island)',
  0xad: 'Poké Mart - alternative music (Cinnabar Island)',
  0xae: 'Pokémon Center (Indigo Plateau)',
  0xaf: "Copycat's house 1F (Saffron City)",
  0xb0: "Copycat's house 2F (Saffron City)",
  0xb1: 'Fighting Dojo (Saffron City)',
  0xb2: 'Pokémon Gym (Saffron City)',
  0xb3: 'House with Pidgey (Saffron City)',
  0xb4: 'Poké Mart (Saffron City)',
  0xb5: 'Silph Co. 1F',
  0xb6: 'Pokémon Center (Saffron City)',
  0xb7: "Mr. Psychic's house (Saffron City)",
  0xb8: 'Gate 1F (Route 15)',
  0xb9: 'Gate 2F (Route 15)',
  0xba: 'Gate 1F (Cycling Road (Route 16)',
  0xbb: 'Gate 2F (Cycling Road (Route 16)',
  0xbc: 'Secret house (Cycling Road) (Route 16)',
  0xbd: 'Route 12 Fishing Brother',
  0xbe: 'Gate 1F (Route 18)',
  0xbf: 'Gate 2F (Route 18)',
  0xc0: 'Seafoam Islands',
  0xc1: 'Badges check gate (Route 22)',
  0xc2: 'Victory Road',
  0xc3: 'Gate 2F (Route 12)',
  0xc4: 'House with NPC and HM moves advice Vermilion City',
  0xc5: "Diglett's Cave",
  0xc6: 'Victory Road',
  0xc7: 'Team Rocket Hideout (B1F)',
  0xc8: 'Team Rocket Hideout (B2F)',
  0xc9: 'Team Rocket Hideout (B3F)',
  0xca: 'Team Rocket Hideout (B4F)',
  0xcb: 'Team Rocket Hideout (Lift)',
  0xcc: 'Unused (Team Rocket Hideout)',
  0xcd: 'Unused (Team Rocket Hideout)',
  0xce: 'Unused (Team Rocket Hideout)',
  0xcf: 'Silph Co. (2F)',
  0xd0: 'Silph Co. (3F)',
  0xd1: 'Silph Co. (4F)',
  0xd2: 'Silph Co. (5F)',
  0xd3: 'Silph Co. (6F)',
  0xd4: 'Silph Co. (7F)',
  0xd5: 'Silph Co. (8F)',
  0xd6: 'Pokémon Mansion (2F)',
  0xd7: 'Pokémon Mansion (3F)',
  0xd8: 'Pokémon Mansion (B1F)',
  0xd9: 'Safari Zone (Area 1)',
  0xda: 'Safari Zone (Area 2)',
  0xdb: 'Safari Zone (Area 3)',
  0xdc: 'Safari Zone (Entrance)',
  0xdd: 'Safari Zone (Rest house 1)',
  0xde: 'Safari Zone (Prize house)',
  0xdf: 'Safari Zone (Rest house 2)',
  0xe0: 'Safari Zone (Rest house 3)',
  0xe1: 'Safari Zone (Rest house 4)',
  0xe2: 'Cerulean Cave',
  0xe3: 'Cerulean Cave 1F',
  0xe4: 'Cerulean Cave B1F',
  0xe5: "Name Rater's house (Lavender Town)",
  0xe6: 'Cerulean City (Gym Badge man)',
  0xe7: 'Unused (Rock Tunnel)',
  0xe8: 'Rock Tunnel',
  0xe9: 'Silph Co. 9F',
  0xea: 'Silph Co. 10F',
  0xeb: 'Silph Co. 11F',
  0xec: 'Silph Co. Lift',
  0xed: '(Invalid)',
  0xee: '(Invalid)',
  0xef: 'Cable Club Trade Center(*)',
  0xf0: 'Cable Club Colosseum(*)',
  0xf1: '(Invalid)',
  0xf2: '(Invalid)',
  0xf3: '(Invalid)',
  0xf4: '(Invalid)',
  0xf5: "Lorelei's room",
  0xf6: "Bruno's room",
  0xf7: "Agatha's room",
  0xf8: 'Summer Beach House (Pokémon Yellow)',
  0xf9: '(Invalid)',
  0xfa: '(Invalid)',
  0xfb: '(Invalid)',
  0xfc: '(Invalid)',
  0xfd: '(Invalid)',
  0xfe: '(Invalid)',
  0xff: ' ?',
};
