export const MapLocations = {
  PalletTown: { name: 'Pallet Town', x: 29, y: 93 },
  Route1: { name: 'Route 1', x: 0, y: 0 },
  ViridianCity: { name: 'Viridian City', x: 0, y: 0 },
  Route2: { name: 'Route 2', x: 0, y: 0 },
  ViridianForest: { name: 'Viridian Forest', x: 0, y: 0 },
  DiglettsCave: { name: "Diglett's Cave", x: 0, y: 0 },
  PewterCity: { name: 'Pewter City', x: 0, y: 0 },
  Route3: { name: 'Route 3', x: 0, y: 0 },
  MtMoon: { name: 'Mt.Moon', x: 0, y: 0 },
  Route4: { name: 'Route 4', x: 0, y: 0 },
  CeruleanCity: { name: 'Cerulean City', x: 0, y: 0 },
  Route24: { name: 'Route 24', x: 0, y: 0 },
  Route25: { name: 'Route 25', x: 0, y: 0 },
  SeaCottage: { name: 'Sea Cottage', x: 0, y: 0 },
  Route5: { name: 'Route 5', x: 0, y: 0 },
  Route6: { name: 'Route 6', x: 0, y: 0 },
  VermilionCity: { name: 'Vermilion City', x: 0, y: 0 },
  SSAnne: { name: 'S.S. Anne', x: 0, y: 0 },
  Route9: { name: 'Route 9', x: 0, y: 0 },
  RockTunnel: { name: 'Rock Tunnel', x: 0, y: 0 },
  Route10: { name: 'Route 10', x: 0, y: 0 },
  LavenderTown: { name: 'Lavender Town', x: 0, y: 0 },
  PokemonTower: { name: 'Pokémon Tower', x: 0, y: 0 },
  Route8: { name: 'Route 8', x: 0, y: 0 },
  Route7: { name: 'Route 7', x: 0, y: 0 },
  CeladonCity: { name: 'Celadon City', x: 0, y: 0 },
  SaffronCity: { name: 'SaffronCity', x: 0, y: 0 },
  Route11: { name: 'Route 11', x: 0, y: 0 },
  Route12: { name: 'Route 12', x: 0, y: 0 },
  Route13: { name: 'Route 13', x: 0, y: 0 },
  Route14: { name: 'Route 14', x: 0, y: 0 },
  Route15: { name: 'Route 15', x: 0, y: 0 },
  Route16: { name: 'Route 16', x: 0, y: 0 },
  Route17: { name: 'Route 17', x: 0, y: 0 },
  Route18: { name: 'Route 18', x: 0, y: 0 },
  FuchsiaCity: { name: 'Fuchsia City', x: 0, y: 0 },
  SafariZone: { name: 'Safari Zone', x: 0, y: 0 },
  SeaRoute19: { name: 'Sea Route 19', x: 0, y: 0 },
  SeafoamIslands: { name: 'Seafoam Islands', x: 0, y: 0 },
  SeaRoute20: { name: 'Sea Route 20', x: 0, y: 0 },
  CinnabarIsland: { name: 'Cinnabar Island', x: 0, y: 0 },
  SeaRoute21: { name: 'Sea Route 21', x: 0, y: 0 },
  Route22: { name: 'Route 22', x: 0, y: 0 },
  Route23: { name: 'Route 23', x: 0, y: 0 },
  VictoryRoad: { name: 'Victory Road', x: 0, y: 0 },
  IndigoPlateau: { name: 'Indigo Plateau', x: 0, y: 0 },
  PowerPlant: { name: 'Power Plant', x: 0, y: 0 },
};
